#!/bin/bash 

cleanup(){
	if [[ -e downloads.html ]] || [[ -e strap.sh ]];
	then 
		rm ~/repos/scripts/strap.sh;
		rm ~/repos/scripts/downloads.html;
	fi 
}


cleanup

wget --https-only https://blackarch.org/strap.sh --quiet -O ~/repos/scripts/strap.sh 
wget --https-only https://blackarch.org/downloads.html --quiet -O ~/repos/scripts/downloads.html 


if [[ -e downloads.html ]]
then 
	chmod +rwx downloads.html
	extracted_cmd=$( cat downloads.html | grep "echo" | grep sha1sum | cut -d ">" -f "1" --complement | cut -d "<" -f "1" );
	echo $extracted_cmd;
	okay_or_not=$( eval $extracted_cmd | cut -d ' ' -f '1' --complement );
	echo $okay_or_not;
	if [[ $okay_or_not = "OK" ]]&& [[ -e strap.sh ]]
	then 
		chmod +x strap.sh 
		eval sudo ./strap.sh 
		echo "DONE"; 
	fi 
fi 

cleanup
