#!/bin/sh

ports(){
  echo ""
  echo "  ssh "
  echo "  smbclient -L \\\\ip\\ -W <workspaceName> -N<if no login>"
  echo "  ftp <ip> -p <portNumber>"
  echo "  telnet <ip> -p <portNumber>"
  echo ""
}
format(){
  echo '  Normal = "\0330]m"'
  echo '  Bold = "\0331]m"'
  echo ""
}
args(){
  echo '
  `$0` -->  The command name or the 0th argument.
  `$1` --> First Argument after the command name.
  `$2` --> Second Argument after the command name.
  `$n` --> The N^th number of Argument after the command name.
  `$@` --> Prints all the arguments starting from "`\$1`" to "`\$n`".
  `$#` --> Returns the count of arguments. '
  echo ""
}
all(){
  format
  args
  ports
}

regex(){
echo '

  * `\d`         --> can be used to represent any character from 0 to 9.
  * `\D`         --> can be used to represent any non numeric character.
  * `.`          --> is used to represent wildcard.
  * `\`          --> are used as an escape sequence.
  * `[]`         --> square brackets are used to match specific set of data.
  * `[^]`        --> The caret is used to exclude specific set of data.
  * `\w`         --> can be used to represent any alphanumeric character.
  * `\W`         --> can be used to represent any non alphanumeric character.
  * `a{n}`       --> Used to find repetitions.
  * `{m,n}`      --> Used to find repetitions can also have a range from m,n.
  * `*`          --> Used to find zero or more repetitions.
  * `+`          --> Used to find one or more repetitions.
  * `?`          --> Used to represent optional character.
  * `()`         --> Used for capturing group and reference back.
  * `(a(bc))`    --> Used for capturing multiple groups and reference back.
  * `(.*)`       --> Used to capture all.
  * `(abc|def)`  --> Matches abc or def.


  ## Whitespacing Regex:

  * `\t`      --> Used to represent 4 spaces or a shift tab.
  * `\n`      --> Used to represent new line.
  * `\r`      --> Used to represent carriage return.
  * `\s`      --> Used to represent whitespace or space.
  * `\S`      --> Used to represent non-whitespace or space.
'
}


if [[ "$1" = "ports" ]]
then
  ports
elif [[ "$1" = "format" ]]
then
  format
elif [[ "$1" = "args" ]]
then
  args
elif [[ "$1" = "regex" ]]
then
  regex
else [[ -z "$1" ]]
  all
fi

