#!/bin/bash 

open(){
	xdg-open "$url" >/dev/null </dev/null >/dev/null 2>&1 & disown
}

# declaring a associative array ...
declare -A classNames; 
classNames[dbms]="btj-eomu-vaq"; 
classNames[java]="mvb-gqqp-pxj"; 
classNames[cnet]="rpd-uprx-oyh"; 
classNames[game]="hdp-dcty-ijz"; 
classNames[inso]="fbx-vebp-sof"; 

# debugging block
# echo ${classNames[dbms]}

# Creating variables for base url ... 
base_url="https://meet.google.com/lookup/";
extend_url="?authuser=0&hs=179";

# If no sys arguments then ask for meet code ...
if [ -z "$1" ]; 
then 
	read -rp "Enter Meeting Code: " code; 
	url=$base_url$code$extend_url;

# If sys argument == python then go to classroom one exception ...
elif [ "$1" == "python" ];
then 
	url="https://classroom.google.com/u/0/c/MzY0NjA0NzUyMzgx"
	
# If any arg one present in classNames array then look for it's value which is a code and open it up ...
elif [ ${classNames[$1]}+_ ]; 
then 
	code=${classNames["$1"]}; 
	url=$base_url$code$extend_url;

else
	url=$base_url;
fi 

# Open the url ...
open
