#!/bin/sh

set -e

bold="\033[1m"
normal="\033[0m"

if [ -z "$1" ]
then
    echo -n ""$bold"Enter a IP Address: "$normal""
    read ip
	echo "$ip";
else
    ip="$1"
	echo "$ip";
fi

url="http://$ip:80/FUZZ/"
echo $url
export -p $IP="$ip"
export -p $URL="$url"


