#!/bin/sh 

commiter(){
	cd ~/repos/links && git add ~/repos/links/. && git commit -m "Added $title" && git push && cd - &
}

if [[ -z "$1" ]]; 
then 
		vim -R ~/repos/links/README.md

elif [[ "$1" == "add" ]]; 
then 
	read -p "Title: " title; 
	read -p "Link: " link; 
	read -p "Description: " desc; 
	baseurl="https://"

	if [ -z "$desc" ];
	then 
		echo "* [$title]($baseurl$link)" >> ~/repos/links/README.md;
		commiter
	elif [ -n "$desc" ];
	then 
		echo "* [$title]($baseurl$link): $desc" >> ~/repos/links/README.md;
		commiter
	fi 


# FIXME: Vim doesn't open from script properly for editing ...
# elif [[ "$1" == "-e" ]]; 
# then 
# 	cd ~/repos/links && sh vim ~/repos/links/README.md && git commit && git push && cd - &

else
	echo "Error [E]: Something went wrong ..."; 
fi



