#!/bin/sh

set -e

bold="\033[1m"
normal="\033[0m"


help(){
    mess=""$bold"NAME $normal
    "$bold"shoot - a tool to take screenshoot and format in markdown

"$bold"SYNOPSIS"$normal"
    "$bold"shoot
    shoot"$normal" --help

"$bold"DESCRIPTION "$normal"
    I have created this tool to take screenshoot (😅) and
    format the output in markdown format.

"$bold"DEPENDENCIES "$normal"
    flameshot
"
    echo "$mess"
}

syscheck(){
    if [ -z "$(which flameshot)" ];
    then
        echo "Please, run Debian: sudo apt install flameshot"
        echo "Please, run Arch: sudo pacman -S flameshot"
        exit
    fi
}

imgcheck(){
    if [ ! -d ./img ];
    then
        mkdir -p ./img
    fi
}

formatmd(){
    if [ -e "$PWD/img/$isosec.png" ];
    then
        echo "!["$isosec"](./img/"$isosec".png)"
    fi
}

syscheck
if [ "$1" = "--help" ];
then
    help
elif [ -n "$1" ];
then
    flameshot gui --delay 3500 --path "$PWD/$1.png" >/dev/null 2>&1
else
    imgcheck
    isosec=`exec date -u +%Y%m%d%H%M%S "$@"`
    # echo "Isosec: "$isosec"" # kept for debugging if needed
    flameshot gui --delay 3500 --path "$PWD/img/$isosec.png" >/dev/null 2>&1
    formatmd
fi

